# Theory and Argumentation

- Develop the initial arguments and theoretical framework of your project.
- Discuss how your project relates to existing theoretical approaches in the literature and how these are further developed and/or applied in your research.
- This theoretical framework will most likely only be at the preliminary stage, but it is important to outline the relationships between the key actors or variables in your project.
- This ‘model’ does not have to be formal and explicit, but you may find it helpful to specify causal relationships in terms of dependent variable(s) (the outcome) and independent variables (the explanatory factors).
- Formulate some preliminary testable hypotheses derived from this ‘model’.
- Outline the key assumptions of your argument, as well as the limits to your topic (temporally and spatially).

# Hypotheses

- The hypotheses provided should state the relationship(s) expected to be observed between variables being used
- The formulation of a hypothesis should make clear whether it involves one- or two-tailed tests (i.e. predict an increase, decrease, or change in the outcome variable)
- There are two types of hypotheses to consider:
    - **Confirmatory Hypotheses**
        - The main focus of the study → what the study is designed to test
        - There should be well-powered analyses of this hypothesis
        - Should be backed up by strong theory leading to hypotheses *a priori*
    - **Exploratory Hypotheses**
        - Hypotheses wish to test but are not the main focus of the study
        - Often seen as secondary hypotheses looking at mechanisms, subgroups, heterogeneous effects, or downstream outcomes
- Should include as many hypotheses as relate to your theory or intervention
- With more than one hypothesis you will need to specify a procedure for handling multiple hypotheses in the inference criteria section of your PAP