---
output: pdf_document
header-includes:
  - \usepackage{multicol}   # Include the multicol package
  - \pagenumbering{gobble}
  - \usepackage{titlesec}
---

\centerline{\Large \textbf{Edward Anders}} \
\centerline{Email: edward.anders@politics.ox.ac.uk | Phone: +44 (0) 07942 927727} \
Researching AI's effects on attitudes. Experience of building early-stage, AI companies working as a deliberate generalist across product, strategy and growth. Interested in the intersection of artificial intelligence, political economy, and democracy.

## Education
\vspace{-3mm}
\begin{multicols}{2}  % Start two-column environment

\raggedright  % Left-align text
\textbf{\normalsize St Antony's College, University of Oxford} \\  % Bold and larger font size
MPhil in Politics (Comparative Government)

\columnbreak  % Move to the right column

\raggedleft  % Right-align text
2024-2026

\end{multicols}
\vspace{-3mm}
Research: Effects of AI-generated content on political attitudes and voting behaviour. \
Supervisor: Prof. Rachel Bernhard, Nuffield College, Oxford.

\begin{multicols}{2}  % Start two-column environment

\raggedright  % Left-align text
\textbf{\normalsize University of Bristol} \\  % Bold and larger font size
BSc Economics and Politics, 1st-Class Honours

\columnbreak  % Move to the right column

\raggedleft  % Right-align text
2018-2021

\end{multicols}

## Professional Experience
\vspace{-3mm}
\begin{multicols}{2}  % Start two-column environment

\raggedright  % Left-align text
\textbf{\normalsize Securely Technology Limited} \\  % Bold and larger font size
Strategy Associate Manager

\columnbreak  % Move to the right column

\raggedleft  % Right-align text
Apr. 2024-present
\end{multicols}

- Employee \#10 at a seed-stage AI startup building GRC software for the B2B enterprise market.
- Built a new Post-Sales department with the Chief Strategy Officer and Chief Executive Officer.
- Architected compliance solutions directly with CISOs and CCOs of Fortune 500 companies.
- Reduced client onboarding time by 75% through automated backend processes.
- Led the development of a new growth marketing process, increasing inbound leads by 200%.

\begin{multicols}{2}  % Start two-column environment

\raggedright  % Left-align text
\textbf{\normalsize Quanterium Technologies (Compose)} \\  % Bold and larger font size
Senior Founder's Associate

\columnbreak  % Move to the right column

\raggedleft  % Right-align text
2021-2024
\end{multicols}

- Employee \#1 working directly with the founders to build an all-in-one inbox. Backed by tier-1 VCs.
- Led product marketing and go-to-market strategy scaling the beta user base from 0 → 1,200 users.
- Owned all aspects of the website, built from scratch using Webflow, Javascript and CSS.
- Implemented product analytics, working with product and engineering to iterate and deploy feedback.
- Led many projects with legal, accounting and investor teams, including operations for an acquisition.

\begin{multicols}{2}  % Start two-column environment

\raggedright  % Left-align text
\textbf{\normalsize Strategy Consulting Internships} \\  % Bold and larger font size
BCG Project, Carnall Farrar, Strategy\&

\columnbreak  % Move to the right column

\raggedleft  % Right-align text
2019-2020
\end{multicols}
- Strategy projects across oil \& gas market entry, NHS hospital efficiency and pharmaceutical pricing.
- Learnt I wanted to be more hands on rather than just making presentations.
- Selected onto Jumpstart's startup-graduate matching programme (top ~1% of 5000+ applicants)

## Skills \& Tooling
- Quantitative and computational research methods inc. machine learning techniques.
- Python, R, Stata, SQL, Git, CSS, Javascript (basic).
- Segment, Webflow, Figma, GitHub.