---
title: "MPhil Politics, Comparative Government"
author: "Edward Anders"
date: "`r Sys.Date()`"
output: pdf_document
zotero: true
header-includes:
  - \usepackage{setspace}
  - \setstretch{1.5}  # Adjust the number for desired line spacing
---


**What factors contribute to the breakdown or survival of authoritarian regimes?**

Authoritarian regimes have been become more democratic in their image. Two thirds of all autocracies hold elections and the breakdown of autocracies by militaristic coup d’etat is now uncommon. With authoritarians such as Putin in Russia still remaining strong, this essay considers what factors contribute to the breakdown and survival of authoritarian regimes.

In this essay I argue that for an autocratic regime to survive, it must nullify two fundamental challenges: revolts from the masses, and overthrow from the elite. If an autocrat can withstand these challengers, it will survive, if it cannot then it will breakdown. I argue that that there are three strategic pillars employed by autocrats in order to survive: legitimisation, repression, and co-optation. Within the framework of these three pillars, this essay proceeds by first arguing that elections are used to both legitimise and co-opt elites into the regime. Secondly, I consider how institutions are also used to solve the problem of elites, before thirdly discussing the role of repressive action against the masses by suppressing protests through military and informational modes.

To set the boundaries for the following analyses, I take an authoritarian regime as a regime which fails to meet Dahl’s (1971) minimalist definition of a democracy which has contested (multi-party) elections which have free and fair participation from the electorate. Therefore, whilst Levestky and Way (2002) identify a newly democratic façade to hybrid autocratic regimes which have democratic aspects, including elections, this essay considers the breakdown of an autocratic regime to be the transition from a non-democratic regime to a democratic one, not a fully authoritarian setup moving closer to democratic norms and being classified as a hybrid regime.

Firstly, I argue that employing elections is a strong contributing factor to the success of an autocracy by legitimising the regime and co-opting elites. Gandhi and Lust-Okar (2009) argue that elections are strategic tools for legitimising the authoritarian to both the masses and elites. If regular elections are held where the popular vote appears to favour the autocrat, they can claim a legitimate mandate, even if the election has been rigged. Autocrats engage in clientelistic behaviours of vote or turnout buying, where local brokers are used by autocrats to offer goods or payments in return for their vote (Frye, Reuter, and Szakonyi, 2019). Despite voters being aware that the authoritarian regime’s success at elections is rigged, Gehlbach, Sonin, and Svolik (2016) show that this is not often an issue for voters trust as they cannot see or know the scale of the corruption. Moreover, the authors note that when ‘independent’ third-party institutions are involved post-election to verify the outcome, this only further entrenches the legitimisation an autocrat can present. Therefore, if elections are successfully used to show legitimate rule, the likelihood of revolt from the masses is reduced, aiding the likelihood of autocratic survival. Moreover, elections can be a useful tool to mitigate threats from opposition elites (e.g., political opponents, party members, or business people). Gandhi and Lust-Okar (2009) also note that elections are an opportunity to see which elites are fighting for the regime, and thus can be used as indicators of which elites are threats and supporters to determine who should be constrained. Once possible threatening elites have been identified through the elections, they can be brought into the close circle of the regime and given patronage such that they have a motivation to maintain the regime since they have something to lose. An example of an autocratic country successfully employing elections is Tanzania. This stable autocracy has held regular elections every five years since 1965. One reason they have been able to do this, unlike in Guinea, is due to the institutions in place which hold autocrats accountable with the help of co-opted elites who are fighting to keep the regime in place.

Secondly, I now turn to autocratic institutions and how they can be utilised to further co-opt elites, constrain autocratic leaders, and promote a legitimate image of autocratic policies. Gandhi and Przeworski (2007) clearly outline how the incorporation of elites into an autocratic regime can be beneficial for preserving and lengthening a regime. If opposing elites are outside of the regime, they have incentives to bring it down and speak out on corruption and incompetence. On the other hand, if elites are within the regime, they have a clear mission to maintain the regime. As noted with the example given above, Guinea had no active elite involvement within the regime’s institutions. This meant that there were commitment problems unsolved for during a change of power such that without elite cooperation, there were asymmetric information and power struggles as the elites had no commitments to the regime. In addition to co-opting elites through institutions, Meng (2020) argues that institutions are effective arbiters of autocratic use of power such that they help prolong the regime by constraining the autocrat themselves. As discussed later, one of the significant factors in an authoritarian regime’s breakdown is the use of repression going too far; therefore, with effective constraints through strong institutions, then autocrats are less likely to become the architects of their own demise. Instead, I next turn to how repression can be a useful tactic for autocrats.

Finally, repression of the masses is a necessary outcome for the survival of an authoritarian regime. I argue that, when necessary, aggressive, violent techniques can be employed, otherwise, modern autocracies are moving towards ‘informational authoritarianism’ to preemptively repress their citizens. Threats to the regime from the masses tend to come in the form of collective action and protest. While Lorentzen (2013) and others make strong arguments that collective action in small doses, particularly at the regional, municipality level, can be useful information gathering devices, autocrats want to avoid notable dissent being amplified. This is where informational authoritarianism is key, particularly for pre-emptively shutting down movements. For example, in China, state censoring focuses on social posts which target collective action, rather than those which directly criticise the state. This is done alongside manipulative misinformation which has the objective of convincing the masses that the government is competent and efficient (Guriev and Treisman, 2019). The best example of this is Lee Kuan Yew of Singapore who consistently emphasises economic strength and competence in order to convince the masses that the government is successful, and mitigating the likelihood that elites will voice concern with corruption, thus reducing the likelihood of revolt.

Although elections, institutions, and repression tactics can appear successful, their success are not guaranteed, and can often backfire and lead to autocratic regime breakdown. Starting with elections, their success in legitimising the government only works if the autocrat can successfully remove credible competition. Importantly, having a strong coalition of parties run against the autocrat can increase the likelihood of the autocrat being successfully defeated in a competitive election; however, Bellin (2014) notes that strong, independent institutions are required to overthrow an autocracy, regardless of whether there are democratic pre-requisites in place. The major issue of institutions for the autocrat is that they can backfire if the autocrat grants too many privileges and power to elites meaning that the autocrat could be broken down from within their own regime. In addition, repression tactics can also lead to unintended consequences of strengthening anti-state attitudes and increasing the likelihood of future revolt (Blaydes, 2018). This counter arguments which highlight the possible unintended consequences of solving authoritarian commitment problems and control of both the masses and elites have to be taken cautiously. Whether the regime is a militaristic, personalistic, or single-party regime will have a significant effect on how the regime handles the challenges it faces. Being a militaristic regime may increased violent repression too far; whereas, personalistic leader may be ousted by elites.

This essay has argued that the use of elections, institutions, and informational — and, at time, violent — repression towards the masses can be successful factors which contribute to the survival of an authoritarian regime. However, the essay concludes that while these are all key factors in the survival of an authoritarian regime, they can also all be the factors which cause the breakdown of an autocratic regime. Elections legitimise the regime, but made too competitive and the autocrat can be legitimately usurped. Institutions give patronage to elites to co-opt their support, but with too much power the elites can take out the autocrat. And, informational authoritarianism can convince the masses that the regime is a success, but when paired with  violence, and suffering, as with Mao, then attitudes against the regime become increasingly sour.